version: "3"
services:
  Dashboard-uplink:
    # if something fails or the server is restarted, the container will restart
    restart: always 
    container_name: Dashboard-uplink
    image: Dashboard-uplink
    build: 
      # build the iris clasifier image from the Dockerfile in the current directory
      context: . 
