version: '3'

services:
  app:
    container_name: dashboard
    restart: always
    build: ./app
    ports:
      - "8501:8501"
    command: streamlit run dashboard.py

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app

